### ISSUE TITLE
Interface not found

### ISSUE THREAD

**Issue by p33994451** [Oliver0804/sync_player#1]
想詢問如果一打開， Master 的服務器 IP 顯示「Interface not found」，是需要打開什麼 Port 或者是 分享器的設定？

還是可以直接輸入 主機自身的 IP？

另外也想詢問影片的名稱和兩台不同樹莓派中的影片長度或名稱，是否需有強制限制要一樣的長度和名稱呢？

還望可獲得解惑！感恩您們的開發！

**Comment by Oliver0804** [comment]
Hi 你好

1. 能否提供ipconfig運行後的資訊，會打印設備網卡的資訊，裝置名稱即可。同步是否能提供作業系統的版本資訊，我一並確認。因在不同設備上會有所不同，導致使用的連線裝置名稱差異，如你能提供我會試試進行修正。
2. 影片長度可以與檔名可以不同，但實際在同步是使用UPD將時間搓記進行傳輸。在長度不同時(子端小於母端長度)可能會導致錯誤。

**Comment by Oliver0804** [comment]
剛剛嘗試整入更多的IP檢查機制，希望他能處理不同的系統，你可以在嘗試看看。

期待你的回覆，感謝。

[#19149](https://github.com/Oliver0804/sync_player/commit/1914988a6baed1fd493fbd3e569df8e8a42d15f9)

**Comment by p33994451** [comment]
您好，感謝您的回覆！

以下是 ipconfig 運行後的資訊，共有兩台，一台是 3B+，另一台是 4B (4GB)；系統都是刷 Raspberry Pi OS (Legacy) May 3rd 2023。

我的網路環境：分享器是水星 H50G。

[https://i.imgur.com/0b10jud.jpg](url)
[https://i.imgur.com/T9tiJ5y.jpg](url)
[https://i.imgur.com/tHSea0g.jpg](url)
[https://i.imgur.com/5Jvess1.jpg](url)

（感恩您！我也再來測試一下新的版本！）

**Comment by p33994451** [comment]
補充回覆：我本來打算測試的方法是，用有 Time code 的影片 （1HR，24FPS）讓兩台同步。

（因為原本有在想要測試兩台都是同樣的時間長度，但是解析度和畫面不同的 Timecode 影片避免畫面混淆；然後也想要瞭解看看同步的效果。）

**Comment by Oliver0804** [comment]
感謝你提供的資訊！

出現這Interface not found應該是沒有認到網卡介面，在新的版本上有多做一些條件來偵測。
(這是讓使用者更容易使用的自動化，不用去查詢Server端的IP)，
如果可以知道自己的Server端，也可嘗試於Master頁籤中直接輸入IP。

有任何問題歡迎在這邊提出，感謝～～

**Comment by p33994451** [comment]
回報：程式更新後，已可順利抓到主機IP！感恩QQ

另外想詢問我這樣的使用方法是否正確？

1. 主機(4B)，Master 頁面開啟影片播放。
2. 子機(3B+)，Slave 頁面輸入主機IP，選擇影片播放。
3. 等待子機和主機同步。

※目前我是兩台都用同一個 Timecode 影片播放，想像是子機雖比較晚使用程式播放，但它的影片播放後，會自動去抓主機的影片播到哪邊？

不過是不是會因為我有安裝 VNC 和 XRDP 用網路遠端看畫面測試的關係，導致同步過程中可能會有錯誤@@.......

目前開XRDP有看到子機顯示「Failed to open LIRC support. You will not be able to use your remote control.」
（但這段訊息開XRDP時會看到，接HDMI輸出時也會，不確定是不是因為只要開機有 VNC 啟動就會影響呢？）

以及「[VO_XV] Shared memory not supported . Reverting to normal Xv.」

[https://i.imgur.com/7bFCs7D.jpg](url)

※我會再測試看看都只接HDMI輸出是否可以；如果有狀況，也會再測試關閉VNC的開機啟動看看。

**Comment by p33994451** [comment]
補充：

如果是改成主機（3B+）接HDMI輸出，但子機（4B）使用VNC，則是子機有一段會顯示『Failed to open VDPAU backend libvdpau_vc4.so: cannot open shared object file: No such file or directory』

但很奇怪的是，它最後並沒有顯示「[VO_XV] Shared memory not supported . Reverting to normal Xv.」。

**Comment by Oliver0804** [comment]
> 回報：程式更新後，已可順利抓到主機IP！感恩QQ
> 
> 另外想詢問我這樣的使用方法是否正確？
> 
> 1. 主機(4B)，Master 頁面開啟影片播放。
> 2. 子機(3B+)，Slave 頁面輸入主機IP，選擇影片播放。
> 3. 等待子機和主機同步。
> 
> ※目前我是兩台都用同一個 Timecode 影片播放，想像是子機雖比較晚使用程式播放，但它的影片播放後，會自動去抓主機的影片播到哪邊？
> 
> 不過是不是會因為我有安裝 VNC 和 XRDP 用網路遠端看畫面測試的關係，導致同步過程中可能會有錯誤@@.......
> 
> 目前開XRDP有看到子機顯示「Failed to open LIRC support. You will not be able to use your remote control.」 （但這段訊息開XRDP時會看到，接HDMI輸出時也會，不確定是不是因為只要開機有 VNC 啟動就會影響呢？）
> 
> 以及「[VO_XV] Shared memory not supported . Reverting to normal Xv.」
> 
> [https://i.imgur.com/7bFCs7D.jpg](url)
> 
> ※我會再測試看看都只接HDMI輸出是否可以；如果有狀況，也會再測試關閉VNC的開機啟動看看。

1.可能來自於樹莓派本身硬體沒支持VDPAU(Video Decode and Presentation API for Unix) 
或者你可以嘗試
```
sudo apt-get install libvdpau-vc4
```
進行安裝，但我想可能是無效的。

我手邊目前的RPI3,RPI4都有任務在進行，所以可能要麻煩你多嘗試看看。

另外如使用 VNC 和 XRDP 多少會有延遲，主要是畫面先同步到子機，子機在透過遠端到你的主機上，所以多少會有延遲，以經驗來說約會有50ms~300ms不等，具體看網路環境，建議是直接接HDMI進行查看。 

[#1 Interface not found
](https://github.com/Oliver0804/sync_player/issues/1?notification_referrer_id=NT_kwDOAH3S3LI4MzE4ODQ2NTIyOjgyNDU5ODA#top)針對本次問題，如果問題已先排除，我先將此議題關閉，如遭遇其他問題再麻煩您發起新的問題，這樣可以讓未來其他人使用上，在項目維護上可以更好的釐清。
